version: '3.9'

services:
volumes:
      - 4200:/Users/venkatramanareddy/desktop/git/dotnet-1/docker-compose.yml
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:80
    volumes:
      - type: bind
        source: ./app
        target: /app

  redis:
    image: redis
    ports:
      - 6379:6379

  mysql:
    image: mysql

volumes:
  app:
    driver: local


